# Generated by Django 4.2.4 on 2023-09-05 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_status', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_status', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputRegister',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('input', models.DateTimeField()),
                ('output', models.DateTimeField(null=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_app.statusregister')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.vehicletype')),
            ],
        ),
    ]
