# Generated by Django 4.2.4 on 2023-09-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscustomer',
            old_name='customer_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='statusregister',
            old_name='register_status',
            new_name='status',
        ),
    ]
